# Generated by Django 5.2.8 on 2025-12-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='content_type',
            field=models.CharField(choices=[('Text', 'text'), ('Video', 'video')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='topic',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='topic_video/'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
