# Generated by Django 5.2.8 on 2025-12-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_topic_content_type_topic_video_alter_topic_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='content_type',
            field=models.CharField(choices=[('text', 'text'), ('video', 'video')], default='text', max_length=10),
        ),
    ]
