# Generated by Django 5.2.8 on 2025-12-09 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_userrole_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='gatway_order_id',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='order_id',
            new_name='order',
        ),
    ]
