# Generated by Django 5.2.8 on 2025-12-08 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_topic_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subcategory',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='content_type',
            new_name='topic_type',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
