# Generated by Django 5.2.8 on 2025-12-11 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_gatway_order_id_order_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollcourse',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.order'),
        ),
    ]
