# Generated by Django 5.2.8 on 2025-12-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_topic_course_enrollcourse_payment_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_picture/'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='mobile_no',
            field=models.CharField(blank=True, default='9999999999', max_length=10),
        ),
        migrations.AddField(
            model_name='userrole',
            name='name',
            field=models.CharField(blank=True, default='User', max_length=250),
        ),
    ]
