# Generated by Django 5.2.8 on 2025-11-30 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_topic_course_enrollcourse_payment_userrole'),
        ('app', '0004_remove_course_category_course_category'),
    ]

    operations = [
    ]
