# Generated by Django 5.2.8 on 2025-12-11 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_enrollcourse_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollcourse',
            name='completed_topics',
        ),
        migrations.RemoveField(
            model_name='enrollcourse',
            name='progress',
        ),
    ]
