# Generated by Django 5.2.8 on 2025-12-12 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_coupon_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='active',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='start_date',
        ),
    ]
